const musicData = [
    // Pop Category
    {
        id: 1,
        title: "Blinding Lights",
        artist: "The Weeknd",
        category: "pop",
        price: 29000,
        emoji: "🌟",
        image: "images/song-1.jpg",
        audio: "audio/song-1.mp3",
        isBestSeller: true,
    },
    {
        id: 2,
        title: "Levitating",
        artist: "Dua Lipa",
        category: "pop",
        price: 25000,
        emoji: "✨",
        image: "images/song-2.jpg",
        audio: "audio/song-2.mp3",
        isBestSeller: true,
    },
    {
        id: 3,
        title: "Anti-Hero",
        artist: "Taylor Swift",
        category: "pop",
        price: 32000,
        emoji: "💔",
        image: "images/song-3.jpg",
        audio: "audio/Anti-hero.mp3",
        isBestSeller: false,
    },
    {
        id: 4,
        title: "Heat Waves",
        artist: "Glass Animals",
        category: "pop",
        price: 24000,
        emoji: "🌊",
        image: "images/song-4.jpg",
        audio: "audio/Heat Waves.mp3",
        isBestSeller: true,
    },
    {
        id: 5,
        title: "As It Was",
        artist: "Harry Styles",
        category: "pop",
        price: 26000,
        emoji: "🎬",
        image: "images/song-5.jpg",
        audio: "audio/As It Was.mp3",
        isBestSeller: false,
    },

    // Rock Category
    {
        id: 6,
        title: "Bohemian Rhapsody",
        artist: "Queen",
        category: "rock",
        price: 30000,
        emoji: "👑",
        image: "images/song-6.jpg",
        audio: "audio/Bohemian Rhapsody.mp3",
        isBestSeller: true,
    },
    {
        id: 7,
        title: "Stairway to Heaven",
        artist: "Led Zeppelin",
        category: "rock",
        price: 31000,
        emoji: "🎸",
        image: "images/song-7.jpg",
        audio: "audio/Stairway to Heaven.mp3",
        isBestSeller: true,
    },
    {
        id: 8,
        title: "Hotel California",
        artist: "Eagles",
        category: "rock",
        price: 28000,
        emoji: "🏨",
        image: "images/song-8.jpg",
        audio: "audio/Hotel California.mp3",
        isBestSeller: false,
    },
    {
        id: 9,
        title: "Sweet Child O' Mine",
        artist: "Guns N' Roses",
        category: "rock",
        price: 27000,
        emoji: "🌹",
        image: "images/song-9.jpg",
        audio: "audio/Sweet Child O' Mine.mp3",
        isBestSeller: false,
    },
    {
        id: 10,
        title: "Enter Sandman",
        artist: "Metallica",
        category: "rock",
        price: 26000,
        emoji: "🌙",
        image: "images/song-10.jpg",
        audio: "audio/Enter Sandman.mp3",
        isBestSeller: false,
    },

    // Hip Hop Category
    {
        id: 11,
        title: "Lose Yourself",
        artist: "Eminem",
        category: "hiphop",
        price: 28000,
        emoji: "🎤",
        image: "images/song-11.jpg",
        audio: "audio/Lose Yourself.mp3",
        isBestSeller: true,
    },
    {
        id: 12,
        title: "No Role Modelz",
        artist: "J. Cole",
        category: "hiphop",
        price: 25000,
        emoji: "👔",
        image: "images/song-12.jpg",
        audio: "audio/No Role Modelz.mp3",
        isBestSeller: false,
    },
    {
        id: 13,
        title: "In Da Club",
        artist: "50 Cent",
        category: "hiphop",
        price: 24000,
        emoji: "🏆",
        image: "images/song-13.jpg",
        audio: "audio/In Da Club.mp3",
        isBestSeller: false,
    },
    {
        id: 14,
        title: "Mo' Money Mo' Problems",
        artist: "The Notorious B.I.G.",
        category: "hiphop",
        price: 27000,
        emoji: "💰",
        image: "images/song-14.jpg",
        audio: "audio/Mo' Money Mo' Problems.mp3",
        isBestSeller: true,
    },
    {
        id: 15,
        title: "HUMBLE.",
        artist: "Kendrick Lamar",
        category: "hiphop",
        price: 26000,
        emoji: "🙏",
        image: "images/song-15.jpg",
        audio: "audio/HUMBLE.mp3",
        isBestSeller: false,
    },

    // Jazz Category
    {
        id: 16,
        title: "Autumn Leaves",
        artist: "Chet Baker",
        category: "jazz",
        price: 22000,
        emoji: "🍂",
        image: "images/song-16.jpg",
        audio: "audio/Autumn Leaves.mp3",
        isBestSeller: false,
    },
    {
        id: 17,
        title: "Take Five",
        artist: "Dave Brubeck",
        category: "jazz",
        price: 23000,
        emoji: "🕐",
        image: "images/song-17.jpg",
        audio: "audio/Take Five.mp3",
        isBestSeller: true,
    },
    {
        id: 18,
        title: "Blue in Green",
        artist: "Bill Evans",
        category: "jazz",
        price: 21000,
        emoji: "💙",
        image: "images/song-18.jpg",
        audio: "audio/Blue in Green.mp3",
        isBestSeller: false,
    },
    {
        id: 19,
        title: "All Blues",
        artist: "Miles Davis",
        category: "jazz",
        price: 24000,
        emoji: "🎷",
        image: "images/song-19.jpg",
        audio: "audio/All Blues.mp3",
        isBestSeller: false,
    },
    {
        id: 20,
        title: "Moanin'",
        artist: "Art Blakey",
        category: "jazz",
        price: 22000,
        emoji: "🎼",
        image: "images/song-20.jpg",
        audio: "audio/Moanin'.mp3",
        isBestSeller: false,
    },

    // Electronic Category
    {
        id: 21,
        title: "Clarity",
        artist: "Zedd ft. Foxes",
        category: "electronic",
        price: 25000,
        emoji: "⚡",
        image: "images/song-21.jpg",
        audio: "audio/Clarity.mp3",
        isBestSeller: false,
    },
    {
        id: 22,
        title: "Titanium",
        artist: "David Guetta ft. Sia",
        category: "electronic",
        price: 27000,
        emoji: "🤖",
        image: "images/song-22.jpg",
        audio: "audio/Titanium.mp3",
        isBestSeller: true,
    },
    {
        id: 23,
        title: "Levels",
        artist: "Avicii",
        category: "electronic",
        price: 26000,
        emoji: "📊",
        image: "images/song-23.jpg",
        audio: "audio/Levels.mp3",
        isBestSeller: false,
    },
    {
        id: 24,
        title: "Wake Me Up",
        artist: "Avicii",
        category: "electronic",
        price: 26000,
        emoji: "🌅",
        image: "images/song-24.jpg",
        audio: "audio/Wake Me Up.mp3",
        isBestSeller: true,
    },
    {
        id: 25,
        title: "Animals",
        artist: "Maroon 5",
        category: "electronic",
        price: 25000,
        emoji: "🦁",
        image: "images/song-25.jpg",
        audio: "audio/Animals.mp3",
        isBestSeller: false,
    },

    // V-Pop Category
    {
        id: 26,
        title: "Tháng Tư Là Lời Nói Dối Của Em",
        artist: "Hà Anh Tuấn",
        category: "vnpop",
        price: 20000,
        emoji: "🇻🇳",
        image: "images/song-26.jpg",
        audio: "audio/Tháng Tư Là Lời Nói Dối Của Em.mp3",
        isBestSeller: true,
    },
    {
        id: 27,
        title: "Em Gái Mưa",
        artist: "Hương Tràm",
        category: "vnpop",
        price: 18000,
        emoji: "🌧️",
        image: "images/song-27.jpg",
        audio: "audio/Em Gái Mưa.mp3",
        isBestSeller: true,
    },
    {
        id: 28,
        title: "Sau Lưng Anh Có Ai Kìa",
        artist: "Thiều Bảo Trâm.",
        category: "vnpop",
        price: 19000,
        emoji: "💔",
        image: "images/song-28.jpg",
        audio: "audio/Sau Lưng Anh Có Ai Kìa.mp3",
        isBestSeller: false,
    },
    {
        id: 29,
        title: "Ngôi Sao Cô Đơn",
        artist: "Jack - J97",
        category: "vnpop",
        price: 17000,
        emoji: "⭐",
        image: "images/song-29.jpg",
        audio: "audio/Ngôi Sao Cô Đơn.mp3",
        isBestSeller: false,
    },
    {
        id: 30,
        title: "Hãy Trao Cho Anh",
        artist: "Sơn Tùng M-TP",
        category: "vnpop",
        price: 19000,
        emoji: "👣",
        image: "images/song-30.jpg",
        audio: "audio/Hãy Trao Cho Anh.mp3",
        isBestSeller: false,
    },
];
